"""
Generates a SOC-style plain-text analyst report from analysis results.
"""
from __future__ import annotations
from datetime import datetime, timezone

from app.services.email_parser import ParsedEmail
from app.services.risk_scoring import ScoringResult, ML_CONFIDENCE_THRESHOLD, CLASSIFICATION_DISPLAY

_SEP = "─" * 72
_THICK = "═" * 72


def _ml_status_lines(
    ml_display_prediction: str | None,
    raw_ml_prediction: str | None,
    ml_confidence: float | None,
) -> list:
    lines = []
    if ml_display_prediction is None:
        lines += ["  ML model unavailable for this analysis.", ""]
        return lines

    conf_pct = f"{(ml_confidence or 0) * 100:.1f}%"
    display_label = CLASSIFICATION_DISPLAY.get(
        ml_display_prediction, ml_display_prediction.replace("_", " ").title()
    )

    if ml_display_prediction == "inconclusive":
        raw_label = CLASSIFICATION_DISPLAY.get(
            raw_ml_prediction or "", (raw_ml_prediction or "").replace("_", " ").title()
        )
        lines += [
            f"  ML Prediction : Inconclusive (below confidence threshold)",
            f"  ML Confidence : {conf_pct}  [threshold: {ML_CONFIDENCE_THRESHOLD*100:.0f}%]",
            f"  Raw ML Result : {raw_label} at {conf_pct} (not used in final classification)",
            "",
            "  NOTE: The ML confidence is below the 65% threshold. The rule-based",
            "  detection engine's findings are the authoritative basis for this report.",
            "",
        ]
    else:
        lines += [
            f"  ML Prediction : {display_label}",
            f"  ML Confidence : {conf_pct}",
            "",
            "  NOTE: ML output is a supporting signal. The final classification",
            "  integrates both ML predictions and rule-based findings.",
            "",
        ]
    return lines


def generate_report(
    parsed: ParsedEmail,
    scoring: ScoringResult,
    findings: list,
    ml_display_prediction: str | None,
    raw_ml_prediction: str | None,
    ml_confidence: float | None,
    analysis_id: int,
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    label = scoring.classification_label

    lines: list = []

    lines += [
        _THICK,
        "  PHISHGUARD AI — SOC ANALYST TRIAGE REPORT",
        _THICK,
        f"  Report ID    : PG-{analysis_id:06d}",
        f"  Generated    : {ts}",
        f"  Tool Version : PhishGuard AI v1.0.0",
        _THICK,
        "",
        "  DISCLAIMER: This report is generated by an automated triage system.",
        "  All findings require human analyst validation before action is taken.",
        "  This tool does NOT fetch, execute, or resolve any URLs or attachments.",
        "  This is a defensive security tool for educational and portfolio use.",
        "",
    ]

    # ── 1. Executive Summary ─────────────────────────────────────────────────
    risk_color_label = {
        "Critical": "⚠ CRITICAL",
        "High":     "▲ HIGH",
        "Medium":   "◆ MEDIUM",
        "Low":      "✓ LOW",
    }.get(scoring.risk_level, scoring.risk_level.upper())

    lines += [
        _SEP,
        "1. EXECUTIVE SUMMARY",
        _SEP,
        f"  Classification : {label.upper()}",
        f"  Risk Score     : {scoring.risk_score}/100",
        f"  Risk Level     : {risk_color_label}",
        "",
        f"  {scoring.summary}",
        "",
        f"  {scoring.score_explanation}",
        "",
    ]

    # Low-risk reassurance
    if scoring.risk_score == 0:
        lines += [
            "  This email does not exhibit characteristics associated with phishing,",
            "  business email compromise, or other known social-engineering tactics.",
            "  No escalation is recommended based on this automated analysis.",
            "",
        ]
    elif scoring.risk_level in ("Critical", "High"):
        lines += [
            "  ⚠ This email exhibits strong indicators of malicious intent.",
            "  Analyst review and escalation are strongly recommended.",
            "  Do not interact with any links, attachments, or sender contact details.",
            "",
        ]

    # ── 2. Email Metadata ────────────────────────────────────────────────────
    lines += [
        _SEP,
        "2. EMAIL METADATA",
        _SEP,
        f"  From     : {parsed.sender or '[not present]'}",
        f"  Reply-To : {parsed.reply_to or '[not present]'}",
        f"  To       : {parsed.recipient or '[not present]'}",
        f"  Subject  : {parsed.subject or '[not present]'}",
        f"  Date     : {parsed.date or '[not present]'}",
        f"  Headers  : {'Present' if parsed.has_headers else 'Not detected (body-only paste)'}",
        "",
    ]

    if parsed.sender and parsed.reply_to and parsed.sender_domain and parsed.reply_to_domain:
        if parsed.sender_domain.lower() != parsed.reply_to_domain.lower():
            lines += [
                f"  ⚠ DOMAIN MISMATCH: From domain '{parsed.sender_domain}' does not match",
                f"    Reply-To domain '{parsed.reply_to_domain}'. Replies are routed to a",
                f"    different domain — a common phishing and BEC evasion technique.",
                "",
            ]

    if parsed.urls:
        lines += ["  Extracted URLs:"]
        for url in parsed.urls[:20]:
            lines.append(f"    - {url[:120]}")
        if len(parsed.urls) > 20:
            lines.append(f"    … and {len(parsed.urls) - 20} more URL(s)")
        lines.append("")

    if parsed.domains:
        lines += [f"  Unique domains detected: {', '.join(parsed.domains[:10])}", ""]

    # ── 3. Machine Learning Analysis ─────────────────────────────────────────
    lines += [
        _SEP,
        "3. MACHINE LEARNING ANALYSIS",
        _SEP,
    ]
    lines.extend(_ml_status_lines(ml_display_prediction, raw_ml_prediction, ml_confidence))

    # ── 4. Detection Findings ────────────────────────────────────────────────
    lines += [
        _SEP,
        "4. DETECTION FINDINGS",
        _SEP,
    ]

    if not findings:
        lines += [
            "  No suspicious indicators detected by the rule-based engine.",
            "  The rule-based analysis is the primary signal for this tool.",
            "",
        ]
    else:
        by_category: dict = {}
        for f in findings:
            by_category.setdefault(f.category, []).append(f)

        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

        for cat, cat_findings in by_category.items():
            sorted_findings = sorted(
                cat_findings, key=lambda f: severity_order.get(f.severity.lower(), 5)
            )
            lines.append(f"  [{cat}]")
            for idx, f in enumerate(sorted_findings, 1):
                lines += [
                    f"    {idx}. [{f.severity.upper()}] {f.finding}",
                    f"       Evidence  : {f.evidence[:250]}",
                    f"       Recommend : {f.recommendation[:250]}",
                    "",
                ]

    # ── 5. Recommended Actions ───────────────────────────────────────────────
    lines += [
        _SEP,
        "5. RECOMMENDED ACTIONS",
        _SEP,
    ]
    for idx, action in enumerate(scoring.recommended_actions, 1):
        lines.append(f"  {idx}. {action}")
    lines.append("")

    # ── 6. Analyst Notes ─────────────────────────────────────────────────────
    lines += [
        _SEP,
        "6. ANALYST NOTES  [Complete after human review]",
        _SEP,
        "",
        "  Disposition   : [ ] Confirmed Malicious  [ ] Benign  [ ] Needs Escalation",
        "  Analyst Notes : ___________________________________________________",
        "  Analyst Name  : ___________________________",
        "  Review Date   : ___________________________",
        "  Ticket / Case : ___________________________",
        "",
    ]

    # ── 7. Limitations ───────────────────────────────────────────────────────
    lines += [
        _SEP,
        "7. TOOL LIMITATIONS",
        _SEP,
        "  - URLs are analyzed structurally only; malicious pages are not fetched.",
        "  - Attachments are not scanned.",
        "  - DKIM/SPF/DMARC authentication is not validated.",
        "  - ML model trained on synthetic data; false positives/negatives are possible.",
        "  - Human analyst review is required before any escalation or remediation.",
        "",
        _SEP,
        "  END OF REPORT — PhishGuard AI  |  PG-" + f"{analysis_id:06d}",
        _SEP,
    ]

    return "\n".join(lines)
